[github]
token = st.secrets["github"]["token"] #  This is safe!
repo_url = "https://github.com/renzorocha1603-source/onlysolutions-uniform-app"

[email]
smtp_server = "smtp.gmail.com"
smtp_port = 587
sender_email = "your_company_automation_email@gmail.com"
sender_password = "your_gmail_app_password_here"
finance_email = "finance_delivery_target@onlysolutions.ca"
